packages:
  - apps/*
  - packages/*

overrides:
  '@eslint/eslintrc>ajv': 6.14.0
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  flatted@<3.4.2: '>=3.4.2'
  js-yaml@>=4.0.0 <4.2.0: '>=4.2.0'
  minimatch@<3.1.4: '>=3.1.4'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  '@eslint/eslintrc>minimatch': 3.1.4
  eslint-plugin-import>minimatch: 9.0.7
  eslint-plugin-jsx-a11y>minimatch: 9.0.7
  eslint-plugin-react>minimatch: 9.0.7
  next@>=15.2.0 <15.5.18: 15.5.18
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: '>=8.5.10'
  tar@<=7.5.15: '>=7.5.16'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
