[mypy]
# Setuptools generates a duplicate source tree when building the API artifact.
exclude = ^build/
ignore_missing_imports = True

[mypy-app.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True
